apiVersion: v2
name: proxysocks
description: A Helm chart for the Giant Swarm Proxy
type: application
version: 0.2.1
icon: https://s.giantswarm.io/app-icons/giantswarm/1/light.svg
appVersion: 0.1.1
annotations:
  io.giantswarm.application.team: cabbage
  io.giantswarm.application.audience: "giantswarm"
